
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8761
#spring:
#  application:
#    name: microservice-discovery-eureka
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka/
#---
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2
#  client:
#      service-url:
#        defaultZone: http://peer1:8761/eureka/

